### PR TITLE
Add support for secret variables in command

### PR DESCRIPTION
**Pull request by npostulart**
According to feature request https://github.com/stepci/stepci/issues/35 this PR adds support for secret variables set as argument.

TODO:

- [ ]  secret variable is still displayed on cli, e.g. using the examples/status.yml and replacing `env.host` with `secret.host`

Secrets should be obfuscated in runner and not returned as plain values in the result object.

### CODE REVIEW

**Comment by mishushakov** [comment]
Mindblowing 🤯

Couple things:

- We use single quotes instead (') of double quotes ("), VueJS convention
- Could you add some comments in `src/lib/utils.ts` that explain what each method does?
- Could you also document the change in the CLI reference (`docs/cli-reference`)?

**Comment by mishushakov** [comment]
Good idea with obfuscating variables. Maybe could look into our [`liquidless`](https://github.com/stepci/liquidless) repo to see how they are processed

**Comment by npostulart** [comment]
> - We use single quotes instead (') of double quotes ("), VueJS convention

My bad, I use Prettier in VSCode and without a config it defaults to double quotes. Maybe we should add Prettier and ESLint for conventions.

> - Could you add some comments in `src/lib/utils.ts` that explain what each method does?

Sure, will do.

> - Could you also document the change in the CLI reference (`docs/cli-reference`)?

Of course 👍

**Comment by mishushakov** [comment]
For linting, I prefer this config: https://standardjs.com
Not sure we need Prettier

**Comment by mishushakov** [comment]
Hey Niklas, do you need anything from me to proceed? I don't think masking is as important now, we could always do it later!

**Comment by npostulart** [comment]
Hey Mish, no I just wanted to make sure to implement the obfuscation before, but if that's not necessary I can undraft the PR.

**Comment by mishushakov** [comment]
Merge it merge it!

**Comment by mishushakov** [comment]
Have added a issue for secret variable masking: https://github.com/stepci/stepci/issues/53

**Pull request merged**
