### PR TITLE
docs: add homebrew installation note

### PR DESCRIPTION
**Pull request by chenrui333**
relates to #24

### CODE REVIEW

**Review by mishushakov — CHANGES_REQUESTED** [review]
Awesome! Thanks for adding Step CI to Homebrew 😄
Could you also add the description to docs/guides/getting-started.md?

Glad to have you as a contributor 🙏

**Review by mishushakov — APPROVED** [review]
Merging! Thank you so much for your contribution to Step CI 🙏

**Comment by chenrui333** [comment]
Thanks @mishushakov!

**Comment by mishushakov** [comment]
Have a happy new year ⭐️

**Pull request merged**
