### PR TITLE
Fix to use some options in githubactions

### PR DESCRIPTION
**Pull request by yu-fuku**
discussion https://github.com/stepci/stepci/discussions/121

### CODE REVIEW

**Comment by mishushakov** [comment]
Cool, thanks for pull request. Have you tested it yet? Does it work as expected?

**Comment by mishushakov** [comment]
Btw. could you also add an option for load-testing (`--load`)?

**Comment by yu-fuku** [comment]
Thanks for comment.

I have tested these to make sure there are no problems.

> Btw. could you also add an option for load-testing (--load)?
OK. Please give me some time to add that option.

**Comment by yu-fuku** [comment]
I added `--load` option.
Please check.

**Comment by mishushakov** [comment]
Looks good 😁
However, I have one concern - what happens if I change the order of the arguments in my action? For example if I skip `envs` and add `noContext` instead?

Here's an example:

```yaml
on: [push]
jobs:
  api_test:
    runs-on: ubuntu-latest
    name: API Tests
    steps:
      - uses: actions/checkout@v3
      - name: Step CI Action
        uses: stepci/stepci
        with:
          workflow: "tests/status.yml"
          noContext: true
```

Does this work properly?

**Comment by mishushakov** [comment]
Ok, does the changes affect when I run it in Docker?

I'm only worried whether the order in which I specify the arguments will become important, eg. I can't specify them in other order

I think you may have to double-check that and you will likely have to add the ARGs to Dockerfile and change your entrypoint.sh accordingly

Have a look at the article:
https://vsupalov.com/docker-arg-env-variable-guide/

Thanks for progress on the issue in any case 😄

**Comment by yu-fuku** [comment]
>Ok, does the changes affect when I run it in Docker?
I'm only worried whether the order in which I specify the arguments will become important, eg. I can't specify them in other order

Sorry I didn't check about running from docker.
And as you say, this will cause wrong order problems in case of docker run.

>I think you may have to double-check that and you will likely have to add the ARGs to Dockerfile and change your >entrypoint.sh accordingly
>
>Have a look at the article:
>https://vsupalov.com/docker-arg-env-variable-guide/

Thanks for the solution idea.
However, ARGs to Dockerfile don't accept input `docker run`, so I used ENVs.

I've updated the pull request, so let me know if there seems to be a problem.

**Comment by yu-fuku** [comment]
We also tested the following test cases with no problems

running from githubactions
```
steps:
      - uses: actions/checkout@v3
      - name: Step CI Action
        uses: stepci/stepci
        with:
          workflow: "tests/status.yml"
          noContext: true
          secrets: "secret1=var1 secret2=var2"
```

running from docker
```
docker run \
       -v "$(pwd)"/tests:/tests \
       -e NO_CONTEXT="true" \
       -e SECRETS="secret1=var1 secret2=var2" \
       ${ImageID} \
       tests/workflow.yml
```

**Comment by mishushakov** [comment]
Great! Will be merging then

**Comment by mishushakov** [comment]
Btw. one thing I forgot 🙈

We want the env variables prefixed by `STEPCI_`, so they are in its own namespace and don't overwrite anything in actions/docker

You can just open a new pull request or just change it in your other PR and I will merge once ready

**Pull request merged**
